### ISSUE TITLE
Can we add student fare as well?

### ISSUE THREAD

**Issue by sNishant011** [kafle1/routeway#2]

**Comment by kafle1** [comment]
Student discount is 35% which is fixed everywhere so when we have the actual rate, I think we can easily calculate students' fare.

**Comment by sonangrai** [comment]
This is not an issue I think it should be as suggestion or improvement.

**Comment by sNishant011** [comment]
Yes but the reason I opened up issue fo this is I can't see discussion tab turned on in this repo.
@kafle1  Please turn on discussions.

**Comment by kafle1** [comment]
done :)
